[colors.primary]
background = "#002b36"
foreground = "#839496"

[colors.cursor]
cursor = "#839496"
text = "#002b36"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"
